# Generated by Django 2.2.1 on 2019-09-11 09:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Realtor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('description', models.TextField()),
                ('phone', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='photos/realtor/%Y/%m/%d')),
                ('hire_date', models.DateTimeField(verbose_name=datetime.datetime(2019, 9, 11, 14, 38, 12, 46441))),
                ('is_mvp', models.BooleanField(default=False)),
            ],
        ),
    ]
