# Generated by Django 2.2.1 on 2019-09-11 09:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtor_app', '0002_auto_20190911_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtor',
            name='hire_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 11, 14, 57, 19, 114783)),
        ),
    ]
